trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: Build
    displayName: Build stage
    jobs:
      - job: Build
        displayName: Build job
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: "unifesprecommendationapi"
              repository: "back"
              command: "build"
              Dockerfile: "**/Dockerfile"
              tags: |
                latest
          - task: Docker@2
            inputs:
              containerRegistry: "unifesprecommendationapi"
              repository: "back"
              command: "push"
              tags: |
                latest
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Azure para Estudantes(1)(539b16da-facf-4e9d-8d71-cf3afc727cd7)'
              appType: 'webAppContainer'
              WebAppName: 'tcc-api-prd-docker'
              DockerNamespace: 'unifesprecommendationapi.azurecr.io'
              DockerRepository: 'back'
              DockerImageTag: 'latest'