# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.1'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'Install node dependencies'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure para Estudantes(1)(539b16da-facf-4e9d-8d71-cf3afc727cd7)'
    appType: 'webAppLinux'
    WebAppName: 'tcc-api-prd'
    packageForLinux: '$(System.DefaultWorkingDirectory)'
    RuntimeStack: 'NODE|14-lts'
    StartupCommand: 'npm run db:migrate && node index'