const Router = require('./router')

const { errorHandler, authorizationChecker } = require('./middlewares')
const authentication = require('./authentication')
const classes = require('./classes')
const classGrids = require('./classGrids')
const courses = require('./courses')
const disciplines = require('./disciplines')
const friendships = require('./friendships')
const meetingTimes = require('./meetingTimes')
const recommendation = require('./recommendation')
const records = require('./records')
const semesters = require('./semesters')
const teachers = require('./teachers')

module.exports = new Router()
    .use(errorHandler)
    .use('/authentication', authentication)
    .use(authorizationChecker)
    .use('/classes', classes)
    .use('/courses', courses)
    .use('/disciplines', disciplines)
    .use('/friendships', friendships)
    .use('/grids', classGrids)
    .use('/meeting-times', meetingTimes)
    .use('/records', records)
    .use('/recommendation', recommendation)
    .use('/semesters', semesters)
    .use('/teachers', teachers)
    .routes()
