const Router = require('./router')

const classGrids = require('./classGrids')
const records = require('./records')
const disciplines = require('./disciplines')
const meetingTimes = require('./meetingTimes')
const classes = require('./classes')

module.exports = new Router()
    .use('/grids', classGrids)
    .use('/records', records)
    .use('/disciplines', disciplines)
    .use('/meeting-times', meetingTimes)
    .use('/classes', classes)
    .routes()
