module.exports = (knex) => knex('disciplines').insert([
    { name: 'Álgebra linear' },
    { name: 'Álgebra linear computacional' },
    { name: 'Álgebra linear II' },
    { name: 'Algoritmos e estruturas de dados I' },
    { name: 'Algoritmos e estruturas de dados II' },
    { name: 'Algoritmos em Bioinformática' },
    { name: 'Análise do Rn' },
    { name: 'Análise Real I' },
    { name: 'Análise Real II' },
    { name: 'Análise de Sinais' },
    { name: 'Anatomia' },
    { name: 'Aplicações de robótica móvel' },
    { name: 'Aprendizado de máquina e reconhecimento de padrões' },
    { name: 'Arquitetura e organização de computadores' },
    { name: 'Aspectos de implementação de banco de dados' },
    { name: 'Avanços em engenharia biomédica' },
    { name: 'Banco de dados' },
    { name: 'Bioengenharia' },
    { name: 'Bioética e biossegurança' },
    { name: 'Bioinformática Avançada' },
    { name: 'Biologia do desenvolvimento' },
    { name: 'Biologia Estrutural' },
    { name: 'Biologia geral' },
    { name: 'Biologia molecular da célula' },
    { name: 'Biologia molecular do gene' },
    { name: 'Biomateriais' },
    { name: 'Biomecânica' },
    { name: 'Bioquímica I' },
    { name: 'Bioquímica II' },
    { name: 'Bioquímica Analítica' },
    { name: 'Biossensores' },
    { name: 'Biotecnologia Ambiental I' },
    { name: 'Biotecnologia Ambiental II' },
    { name: 'Biotecnologia Animal' },
    { name: 'Biotecnologia Vegetal' },
    { name: 'Biotecnologia de Energias Renováveis I' },
    { name: 'Biotecnologia de energias renovaveis II' },
    { name: 'Blendas Poliméricas' },
    { name: 'Botânica e fisiologia vegetal' },
    { name: 'Cálculo em uma variável' },
    { name: 'Cálculo em várias variáveis' },
    { name: 'Cálculo numérico' },
    { name: 'Cerâmicas refratárias' },
    { name: 'Ciência e tecnologia dos materiais' },
    { name: 'Ciência, tecnologia e sociedade' },
    { name: 'Ciência, tecnologia, sociedade e ambiente' },
    { name: 'Circuitos digitais' },
    { name: 'Circuitos elétricos I' },
    { name: 'Circuitos elétricos II' },
    { name: 'Compiladores' },
    { name: 'Computação gráfica' },
    { name: 'Condicionamento Analógico de Sinais' },
    { name: 'Controle de sistemas dinâmicos' },
    { name: 'Controle digital' },
    { name: 'Corrosão e degradação de materiais' },
    { name: 'Cultura digital' },
    { name: 'Cultura dos Jogos Digitais' },
    { name: 'Desenho Técnico Assistido por Computador' },
    { name: 'Desenho técnico básico' },
    { name: 'Desenvolvimento de Games' },
    { name: 'Desenvolvimento Integrado de Produtos' },
    { name: 'Desenvolvimento de Novos Negócios em Engenharia Biomédica' },
    { name: 'Direitos humanos, multiculturalismo e C&T' },
    { name: 'Eletrônica avançada' },
    { name: 'Ecologia Avançada' },
    { name: 'Econometria' },
    { name: 'Efeitos Biológicos das Radiações Ionizantes' },
    { name: 'Elementos de Álgebra' },
    { name: 'Empreendedorismo' },
    { name: 'Empreendedorismo em biotecnologia' },
    { name: 'Engenharia bioquímica I' },
    { name: 'Engenharia bioquímica II' },
    { name: 'Engenharia clínica hospitalar' },
    { name: 'Engenharia de produtos cerâmicos' },
    { name: 'Engenharia de software' },
    { name: 'Engenharia médica aplicada' },
    { name: 'Engenharia Tecidual e Medicina Regenerativa' },
    { name: 'Ensaios de materiais' },
    { name: 'Equações diferenciais ordinárias' },
    { name: 'Equações diferenciais parciais' },
    { name: 'Espaços métricos' },
    { name: 'Estrutura e propriedades de polímeros' },
    { name: 'Farmacologia Molecular' },
    { name: 'Fenômenos de transporte' },
    { name: 'Fenômenos do contínuo' },
    { name: 'Fenômenos do contínuo experimental' },
    { name: 'Fenômenos eletromagnéticos' },
    { name: 'Fenômenos eletromagnéticos experimental' },
    { name: 'Fenômenos mecânicos' },
    { name: 'Fenômenos mecânicos experimental' },
    { name: 'Física geral' },
    { name: 'Física moderna' },
    { name: 'Fisiologia humana I' },
    { name: 'Fisiologia humana II' },
    { name: 'Fisiopatologia Cardiorrespiratória' },
    { name: 'Fisiopatologia clínica dos sistemas humanos' },
    { name: 'Funções analíticas' },
    { name: 'Fundamentos de biologia moderna' },
    { name: 'Fundamentos de engenharia bioquímica' },
    { name: 'Fundamentos de matlab aplicado à engenharia' },
    { name: 'Fundamentos de mecânica celeste' },
    { name: 'Geometria analítica' },
    { name: 'Gestão da Inovação' },
    { name: 'Gestão de projetos' },
    { name: 'Imagens biomédicas' },
    { name: 'Imunologia Aplicada' },
    { name: 'Imunologia Geral' },
    { name: 'Inferência e análise de regressão' },
    { name: 'Inteligência artificial' },
    { name: 'Interação humano-computador' },
    { name: 'Introdução à análise funcional' },
    { name: 'Introdução à bioinformática' },
    { name: 'Introdução à biologia de sistemas' },
    { name: 'Introdução à biotecnologia' },
    { name: 'Introdução à ecologia' },
    { name: 'Introdução à eletrotécnica' },
    { name: 'Introdução à engenharia biomédica' },
    { name: 'Introdução à engenharia de materiais' },
    { name: 'Introdução à engenharia financeira' },
    { name: 'Introdução à geometria diferencial' },
    { name: 'Introdução à nanotecnologia' },
    { name: 'Introdução à Neurociência' },
    { name: 'Introdução à ótica biomédica' },
    { name: 'Introdução à pesquisa operacional' },
    { name: 'Introdução às Redes Neurais Artificiais' },
    { name: 'Introdução à Teoria dos Sistemas Dinâmicos' },
    { name: 'Instrumentos biomédicos I' },
    { name: 'Instrumentos biomédicos II' },
    { name: 'Instrumentos Eletromédicos' },
    { name: 'Laboratório avançado de métodos ágeis e software' },
    { name: 'Laboratório de biologia molecular e celular' },
    { name: 'Laboratório de bioquímica' },
    { name: 'Laboratório de bioquímica analítica' },
    { name: 'Laboratório de circuitos elétricos' },
    { name: 'Laboratório de eletrônica digital' },
    { name: 'Laboratório de estatística aplicada' },
    { name: 'Laboratório de engenharia bioquímica' },
    { name: 'Laboratório de matemática' },
    { name: 'Laboratório de microbiologia' },
    { name: 'Laboratório de sistemas computacionais: arquitetura e organização de computadores' },
    { name: 'Laboratório de sistemas computacionais: circuitos digitais' },
    { name: 'Laboratório de sistemas computacionais: compiladores' },
    { name: 'Laboratório de sistemas computacionais: engenharia de sistemas' },
    { name: 'Laboratório de sistemas computacionais: Comunicação Digital' },
    { name: 'Laboratório de sistemas computacionais: sistemas operacionais' },
    { name: 'Laboratório de usabilidade na web' },
    { name: 'Linguagens formais e autômatos' },
    { name: 'Lógica de programação' },
    { name: 'Manufatura Aditiva' },
    { name: 'Marketing Estratégico' },
    { name: 'Matemática discreta' },
    { name: 'Matemática geral' },
    { name: 'Materiais aeroespaciais' },
    { name: 'Materiais cerâmicos' },
    { name: 'Materiais compósitos' },
    { name: 'Materiais de construção civil' },
    { name: 'Materiais elétricos' },
    { name: 'Materiais metálicos' },
    { name: 'Materiais poliméricos' },
    { name: 'Matérias-primas cerâmicas' },
    { name: 'Mecânica geral' },
    { name: 'Metalurgia extrativa' },
    { name: 'Metalurgia física' },
    { name: 'Metalurgia mecânica' },
    { name: 'Metodologia da pesquisa e comunicação científica' },
    { name: 'Métodos Avançados em Processamento de Imagens Biomédicas' },
    { name: 'Métodos Estatísticos Multivariados' },
    { name: 'Métodos Matemáticos para a Engenharia' },
    { name: 'Métodos numéricos para equações diferenciais' },
    { name: 'Microbiologia aplicada e industrial' },
    { name: 'Microbiologia geral' },
    { name: 'Microeconomia' },
    { name: 'Modelagem computacional' },
    { name: 'Modelagem de Dados' },
    { name: 'Modelagem Molecular' },
    { name: 'Modelos Animais' },
    { name: 'Multimídia' },
    { name: 'Otimização inteira' },
    { name: 'Otimização linear' },
    { name: 'Otimização não linear' },
    { name: 'Paradigmas da programação' },
    { name: 'Planejamento de Experimentos' },
    { name: 'Prática em Projetos Extensionistas I' },
    { name: 'Práticas de extensão e divulgação científica' },
    { name: 'Práticas em Projetos Extensionistas II' },
    { name: 'Probabilidade' },
    { name: 'Probabilidade e estatística' },
    { name: 'Processamento de imagens' },
    { name: 'Processamento de materiais cerâmicos' },
    { name: 'Processamento de materiais metálicos' },
    { name: 'Processamento de sinais' },
    { name: 'Processamento de sinais biomédicos' },
    { name: 'Processamento de termofíxos e elastômeros' },
    { name: 'Processamento de termoplásticos' },
    { name: 'Programação concorrente e distribuída' },
    { name: 'Programação orientada a objetos' },
    { name: 'Programação paralela e processamento de alto desempenho' },
    { name: 'Projeto e análise de algoritmos' },
    { name: 'Projeto orientado a objetos' },
    { name: 'Projetos em engenharia de computação' },
    { name: 'Proteômica' },
    { name: 'Prototipagem e Manufatura Aditiva' },
    { name: 'Qualidade' },
    { name: 'Química analítica' },
    { name: 'Química geral' },
    { name: 'Química geral experimental' },
    { name: 'Química inorgânica' },
    { name: 'Química Medicinal I' },
    { name: 'Quimica Medicinal II' },
    { name: 'Química orgânica' },
    { name: 'Química orgânica experimental' },
    { name: 'Radioterapia para Engenharia' },
    { name: 'Realidade virtual e aumentada' },
    { name: 'Reciclagem de materiais' },
    { name: 'Redes de computadores' },
    { name: 'Redes Neurais e Aprendizado Profundo' },
    { name: 'Relações étnico-raciais e cultura afro-brasileira e indígena' },
    { name: 'Reologia dos materiais' },
    { name: 'Resistência dos materiais' },
    { name: 'Resolução de problemas via modelagem matemática' },
    { name: 'Segurança computacional' },
    { name: 'Seleção de materiais' },
    { name: 'Seminários interdisciplinares' },
    { name: 'Séries e equações diferenciais ordinárias' },
    { name: 'Síntese de polímeros' },
    { name: 'Sistemas distribuídos' },
    { name: 'Sistemas embarcados' },
    { name: 'Sistemas mecânicos' },
    { name: 'Sistemas operacionais' },
    { name: 'Sustentabilidade no Gerenciamento de Resíduos' },
    { name: 'Técnicas experimentais' },
    { name: 'Tecnologia e meio ambiente' },
    { name: 'Tecnologia em tintas e vernizes' },
    { name: 'Tecnologia social: práxis e contra-hegemonia' },
    { name: 'Teoria dos grafos' },
    { name: 'Teoria dos números e criptografia' },
    { name: 'Teorias administrativas' },
    { name: 'Termodinâmica dos sólidos' },
    { name: 'Termodinâmica química' },
    { name: 'Tópicos em estatística' },
    { name: 'Tópicos em matemática computacional I' },
    { name: 'Tópicos em Ciência e Tecnologia III' },
    { name: 'Tópicos em tecnologia da computação I' },
    { name: 'Tópicos em tecnologia da computação II' },
    { name: 'Tópicos em tecnologia da computação III' },
    { name: 'Tópicos em tecnologia da computação IV' },
    { name: 'Tópicos em tecnologia da computação V' },
    { name: 'Tópicos em Ressonância Magnética Nuclear' },
    { name: 'Tópicos especiais em ciência e engenharia de materiais II' },
    { name: 'Trajetorias da Inovação' },
    { name: 'Transdução de grandezas biomédicas' },
    { name: 'Tratamentos térmicos' },
    { name: 'Validação e verificação de software' },
    { name: 'Vidros, vitrocerâmicas e vidrados' },
    { name: 'ECOS-EC' },
    { name: 'Biofísica' },
    { name: 'Soft Skills na Engenharia' },
    { name: 'Elaboração de Trabalhos Científicos e Tecnológicos em Computação' },
    { name: 'Telemedicina' },
    { name: 'Tópicos especiais em ciência e engenharia de materiais I' },
    { name: 'Metalurgia do Pó' },
    { name: 'Trabalho de Graduação' },
    { name: 'Segurança da Informação' },
    { name: 'Alteridade e Diversidade no Brasil: Implicações para Política de Ciência e Tecnologia' },
    { name: 'Análise de Investimentos e Riscos' },
    { name: 'Economia Matemática' },
    { name: 'Mudança do Clima e Sociedade' },
    { name: 'Tópicos em Ciência e Tecnologia I' },
    { name: 'Tópicos Interdisciplinares em Computação I' },
    { name: 'Códigos Corretores de Erros' },
    { name: 'Economia, Sociedade e Ambiente' },
    { name: 'Tópicos em Ciência e Tecnologia II' },
    { name: 'Tópicos Interdisciplinares em Computação II' },
    { name: 'Bioestatística' },
    { name: 'Fluxos em Redes' },
    { name: 'Tópicos Interdisciplinares em Computação IV' },
    { name: 'Computação Bioinspirada' },
    { name: 'Métodos Probabilíticos em Pesquisa operacional' },
    { name: 'Tópicos em Ciência e Tecnologia IV' },
    { name: 'Séries Temporais e Previsões' },
    { name: 'Introdução à Aeroelasticidade' },
    { name: 'Simulação de Sistemas' },
    { name: 'Tópicos Interdisciplinares em Computação III' }
])
