module.exports = async (knex) => {
    const disciplines = await knex.select('id', 'name').from('disciplines')
    const disciplineIdByName = {}
    disciplines.forEach((discipline) => {
        const { id, name } = discipline
        disciplineIdByName[name.toUpperCase()] = id
    })

    const getDisciplineIdByName = (disciplineName) => disciplineIdByName[disciplineName.toUpperCase()]

    return knex('discipline_prerequisites').insert([
        { discipline_id: getDisciplineIdByName('Álgebra Linear'), required_discipline_id: getDisciplineIdByName('Geometria Analítica') },
        { discipline_id: getDisciplineIdByName('Álgebra Linear II'), required_discipline_id: getDisciplineIdByName('Álgebra Linear') },
        { discipline_id: getDisciplineIdByName('Álgebra Linear Computacional'), required_discipline_id: getDisciplineIdByName('Cálculo Numérico') },
        { discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados II'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I') },
        { discipline_id: getDisciplineIdByName('Algoritmos em Bioinformática'), required_discipline_id: getDisciplineIdByName('Linguagem de Programação') },
        { discipline_id: getDisciplineIdByName('Análise de Sinais'), required_discipline_id: getDisciplineIdByName('Séries e Equações Diferenciais Ordinárias') },
        { discipline_id: getDisciplineIdByName('Arquitetura e Organização de Computadores'), required_discipline_id: getDisciplineIdByName('Circuitos Digitais') },
        { discipline_id: getDisciplineIdByName('Aprendizado de Máquina e Reconhecimento de Padrões'), required_discipline_id: getDisciplineIdByName('Probabilidade e Estatísti') },
        { discipline_id: getDisciplineIdByName('Aprendizado de Máquina e Reconhecimento de Padrões'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Aspectos de implementação de banco de dados'), required_discipline_id: getDisciplineIdByName('Banco de Dados') },
        { discipline_id: getDisciplineIdByName('Algoritmos em Bioinformática'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Análise de Investimentos de Riscos'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },

        { discipline_id: getDisciplineIdByName('Banco de Dados'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I') },
        { discipline_id: getDisciplineIdByName('Bioinformática Avançada'), required_discipline_id: getDisciplineIdByName('Introdução à Bioinformática') },
        { discipline_id: getDisciplineIdByName('Bioestatística'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Biomateriais'), required_discipline_id: getDisciplineIdByName('Química Geral') },

        { discipline_id: getDisciplineIdByName('Cálculo Numérico'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Cálculo Numérico'), required_discipline_id: getDisciplineIdByName('Geometria Analítica') },
        { discipline_id: getDisciplineIdByName('Cálculo em Várias Variáveis'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Cálculo em Várias Variáveis'), required_discipline_id: getDisciplineIdByName('Geometria Analítica') },
        { discipline_id: getDisciplineIdByName('Circuitos Elétricos II'), required_discipline_id: getDisciplineIdByName('Circuitos Elétricos I') },
        { discipline_id: getDisciplineIdByName('Circuitos Elétricos II'), required_discipline_id: getDisciplineIdByName('Fenômenos Eletromagnéticos') },
        { discipline_id: getDisciplineIdByName('Compiladores'), required_discipline_id: getDisciplineIdByName('Linguagens Formais e Autômatos') },
        { discipline_id: getDisciplineIdByName('Controle de Sistemas Dinâmicos'), required_discipline_id: getDisciplineIdByName('Análise de Sinais') },
        { discipline_id: getDisciplineIdByName('Controle de Sistemas Dinâmicos'), required_discipline_id: getDisciplineIdByName('Circuitos Elétricos II') },
        { discipline_id: getDisciplineIdByName('Computação Gráfica'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I') },
        { discipline_id: getDisciplineIdByName('Computação Bioinspirada'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Códigos Corretores de Erros'), required_discipline_id: getDisciplineIdByName('Álgebra Linear') },
        { discipline_id: getDisciplineIdByName('Computação Bioinspirada'), required_discipline_id: getDisciplineIdByName('Algoritmo e Estrutura de Dados I') },

        { discipline_id: getDisciplineIdByName('Desenvolvimento de Aplicações Robóticas'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },

        { discipline_id: getDisciplineIdByName('Engenharia de Software'), required_discipline_id: getDisciplineIdByName('Programação Orientada a Objetos') },
        { discipline_id: getDisciplineIdByName('Ecologia Avançada'), required_discipline_id: getDisciplineIdByName('Introdução à Ecologia') },
        { discipline_id: getDisciplineIdByName('Econometria'), required_discipline_id: getDisciplineIdByName('Cálculo em Várias Variáveis') },
        { discipline_id: getDisciplineIdByName('Econometria'), required_discipline_id: getDisciplineIdByName('Probabilidade e Estatística') },
        { discipline_id: getDisciplineIdByName('Economia Matemática'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Economia Monetária e Bancos'), required_discipline_id: getDisciplineIdByName('Cálculo em Várias Variáveis') },
        { discipline_id: getDisciplineIdByName('Economia Monetária e Bancos'), required_discipline_id: getDisciplineIdByName('Probabilidade e Estatística') },
        { discipline_id: getDisciplineIdByName('Engenharia Tecidual e Medicina Regenerativa'), required_discipline_id: getDisciplineIdByName('Biologia Molecular da Célula') },
        { discipline_id: getDisciplineIdByName('Engenharia Tecidual e Medicina Regenerativa'), required_discipline_id: getDisciplineIdByName('Fisiologia Humana') },

        { discipline_id: getDisciplineIdByName('Fundamentos de Mecânica Celeste'), required_discipline_id: getDisciplineIdByName('Fenômenos Mecânicos') },
        { discipline_id: getDisciplineIdByName('Fundamentos de Mecânica Celeste'), required_discipline_id: getDisciplineIdByName('Séries e Equações Diferenciais') },
        { discipline_id: getDisciplineIdByName('Fluxos em Redes'), required_discipline_id: getDisciplineIdByName('Otimização Linear') },

        { discipline_id: getDisciplineIdByName('Introdução à Engenharia Financeira'), required_discipline_id: getDisciplineIdByName('Cálculo em Várias Variáveis') },
        { discipline_id: getDisciplineIdByName('Introdução à Engenharia Financeira'), required_discipline_id: getDisciplineIdByName('Probabilidade e Estatística') },
        { discipline_id: getDisciplineIdByName('Interação humano- computador'), required_discipline_id: getDisciplineIdByName(' Programação Orientada a Objetos') },
        { discipline_id: getDisciplineIdByName('Inteligência Artificial'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I') },
        { discipline_id: getDisciplineIdByName('Introdução a Pesquisa Operacional'), required_discipline_id: getDisciplineIdByName('Álgebra Linear') },
        { discipline_id: getDisciplineIdByName('Introdução às Redes Neurais Artificiais'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Introdução à Aeroelasticidade'), required_discipline_id: getDisciplineIdByName('Fenômenos Mecânicos') },
        { discipline_id: getDisciplineIdByName('Introdução à Aeroelasticidade'), required_discipline_id: getDisciplineIdByName('Cálculo Numérico') },
        { discipline_id: getDisciplineIdByName('Introdução à Bioinformática'), required_discipline_id: getDisciplineIdByName('Biologia Molecular da Célula') },
        { discipline_id: getDisciplineIdByName('Introdução à Bioinformática'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Introdução à Biologia de Sistemas'), required_discipline_id: getDisciplineIdByName('Biologia Molecular da Célula') },

        { discipline_id: getDisciplineIdByName('Laboratório de Circuitos Elétricos'), required_discipline_id: getDisciplineIdByName('Circuitos Elétricos I') },
        { discipline_id: getDisciplineIdByName('Laboratório de Circuitos Elétricos'), required_discipline_id: getDisciplineIdByName('Fenômenos Eletromagnéticos') },
        { discipline_id: getDisciplineIdByName('Laboratório de Eletrônica Digital'), required_discipline_id: getDisciplineIdByName('Circuitos Digitais') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Arquitetura e Organização de Computadores'), required_discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Circuitos Digitais') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Arquitetura e Organização de Computadores'), required_discipline_id: getDisciplineIdByName('Arquitetura e Organização de Computadores') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Circuitos Digitais'), required_discipline_id: getDisciplineIdByName('Circuitos Digitais') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Compiladores'), required_discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Engenharia de Sistemas') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Compiladores'), required_discipline_id: getDisciplineIdByName('Compiladores') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Comunicação Digital'), required_discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Sistemas Operacionais') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Comunicação Digital'), required_discipline_id: getDisciplineIdByName('Redes de Computadores') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Engenharia de Sistemas'), required_discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Arquitetura e Organização de Computadores') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Sistemas Operacionais'), required_discipline_id: getDisciplineIdByName('Sistemas Operacionais') },
        { discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Sistemas Operacionais'), required_discipline_id: getDisciplineIdByName('Laboratório de Sistemas Computacionais: Compiladores') },
        { discipline_id: getDisciplineIdByName('Laboratório de sistemas computacionais: Comunicação Digital'), required_discipline_id: getDisciplineIdByName('Matemática Discreta') },
        { discipline_id: getDisciplineIdByName('Laboratório de usabilidade na web'), required_discipline_id: getDisciplineIdByName('Programação Orientada a Objetos') },
        { discipline_id: getDisciplineIdByName('Linguagens Formais e Autômatos'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Linguagens Formais e Autômatos'), required_discipline_id: getDisciplineIdByName('Matemática Discreta') },
        { discipline_id: getDisciplineIdByName('Laboratório de Bioquímica'), required_discipline_id: getDisciplineIdByName('Bioquímica I') },
        { discipline_id: getDisciplineIdByName('Laboratório de Bioquímica'), required_discipline_id: getDisciplineIdByName('Biologia Molecular do Gene') },
        { discipline_id: getDisciplineIdByName('Laboratório de Biologia Molecular e Celular'), required_discipline_id: getDisciplineIdByName('Biologia Molecular da Célula') },
        { discipline_id: getDisciplineIdByName('Laboratório de Microbiologia'), required_discipline_id: getDisciplineIdByName('Microbiologia Geral') },
        { discipline_id: getDisciplineIdByName('Laboratório de Engenharia Bioquímica'), required_discipline_id: getDisciplineIdByName('Engenharia Bioquímica I') },

        { discipline_id: getDisciplineIdByName('Multimídia'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Mecânica Geral'), required_discipline_id: getDisciplineIdByName('Fenômenos Mecânicos') },
        { discipline_id: getDisciplineIdByName('Mecânica Geral'), required_discipline_id: getDisciplineIdByName('Geometria Analítica') },
        { discipline_id: getDisciplineIdByName('Materiais Elétricos'), required_discipline_id: getDisciplineIdByName('Fenômenos Eletromagnéticos') },
        { discipline_id: getDisciplineIdByName('Métodos Numéricos para Equações Diferenciais'), required_discipline_id: getDisciplineIdByName('Cálculo Numérico') },
        { discipline_id: getDisciplineIdByName('Métodos Numéricos para Equações Diferenciais'), required_discipline_id: getDisciplineIdByName('Álgebra Linear') },
        { discipline_id: getDisciplineIdByName('Métodos Numéricos para Equações Diferenciais'), required_discipline_id: getDisciplineIdByName('Séries e Equações Diferenciais') },
        { discipline_id: getDisciplineIdByName('Modelagem Computacional'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Modelagem Computacional'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Métodos Probabilísticos em Pesquisa Operacional'), required_discipline_id: getDisciplineIdByName('Probabilidade e Estatística') },
        { discipline_id: getDisciplineIdByName('Métodos Probabilísticos em Pesquisa Operacional'), required_discipline_id: getDisciplineIdByName('Otimização Linear') },

        { discipline_id: getDisciplineIdByName('Organização Industrial'), required_discipline_id: getDisciplineIdByName('Cálculo em Várias Variáveis') },
        { discipline_id: getDisciplineIdByName('Otimização Inteira'), required_discipline_id: getDisciplineIdByName('Otimização Linear') },

        { discipline_id: getDisciplineIdByName('Qualidade'), required_discipline_id: getDisciplineIdByName('Probabilidade e Estatística') },

        { discipline_id: getDisciplineIdByName('Paradigmas da Programação'), required_discipline_id: getDisciplineIdByName('Programação Orientada a Objetos') },
        { discipline_id: getDisciplineIdByName('Probabilidade e Estatística'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Processamento de Imagens'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Processamento de Imagens'), required_discipline_id: getDisciplineIdByName('Series e Equações Diferenciais') },
        { discipline_id: getDisciplineIdByName('Processamento de Sinais'), required_discipline_id: getDisciplineIdByName('Análise de Sinais') },
        { discipline_id: getDisciplineIdByName('Processamento de Sinais'), required_discipline_id: getDisciplineIdByName('Algoritmos em Bioinformática') },
        { discipline_id: getDisciplineIdByName('Programação Orientada a Objetos'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I') },
        { discipline_id: getDisciplineIdByName('Programação Concorrente e Distribuída'), required_discipline_id: getDisciplineIdByName('Sistemas Operacionais') },
        { discipline_id: getDisciplineIdByName('Programação Paralela e Processamento de Alto Desempenho'), required_discipline_id: getDisciplineIdByName('Programação Concorrente e Distribuída') },
        { discipline_id: getDisciplineIdByName('Projeto e Análise de Algoritmos'), required_discipline_id: getDisciplineIdByName('Matemática Discreta') },
        { discipline_id: getDisciplineIdByName('Projeto e Análise de Algoritmos'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados II') },
        { discipline_id: getDisciplineIdByName('Projeto Orientado a Objetos'), required_discipline_id: getDisciplineIdByName('Programação Orientada a Objetos') },
        { discipline_id: getDisciplineIdByName('Projeto de Sistemas Digitais'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Projeto de Sistemas Digitais'), required_discipline_id: getDisciplineIdByName('Arquitetura e Organização de Computadores') },

        { discipline_id: getDisciplineIdByName('Segurança da Informação'), required_discipline_id: getDisciplineIdByName('Sistemas Operacionais') },
        { discipline_id: getDisciplineIdByName('Segurança Computacional'), required_discipline_id: getDisciplineIdByName('Sistemas Operacionais') },
        { discipline_id: getDisciplineIdByName('Seleção de Materiais'), required_discipline_id: getDisciplineIdByName('Ciência e Tecnologia dos Materiais') },
        { discipline_id: getDisciplineIdByName('Séries e Equações Diferenciais Ordinárias'), required_discipline_id: getDisciplineIdByName('Cálculo em Uma Variável') },
        { discipline_id: getDisciplineIdByName('Séries Temporais e Previsões'), required_discipline_id: getDisciplineIdByName('Inferência e Análise de Regressão') },
        { discipline_id: getDisciplineIdByName('Simulação de Sistemas'), required_discipline_id: getDisciplineIdByName('Lógica de Programação ') },
        { discipline_id: getDisciplineIdByName('Simulação de Sistemas'), required_discipline_id: getDisciplineIdByName('Probabilidade') },
        { discipline_id: getDisciplineIdByName('Sistemas Distribuídos'), required_discipline_id: getDisciplineIdByName('Sistemas Operacionais') },
        { discipline_id: getDisciplineIdByName('Sistemas Embarcados'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados') },
        { discipline_id: getDisciplineIdByName('Sistemas Embarcados'), required_discipline_id: getDisciplineIdByName('Arquitetura e Organização de Computadores') },
        { discipline_id: getDisciplineIdByName('Sistemas Operacionais'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estruturas de Dados I') },
        { discipline_id: getDisciplineIdByName('Sistemas Robóticos'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Sistemas Robóticos'), required_discipline_id: getDisciplineIdByName('Fenômenos Mecânicos') },
        { discipline_id: getDisciplineIdByName('Simulação de Sistemas'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Simulação de Sistemas'), required_discipline_id: getDisciplineIdByName('Probabilidade') },

        { discipline_id: getDisciplineIdByName('Realidade Virtual e Aumentada'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Recuperação de Informação Multimídia'), required_discipline_id: getDisciplineIdByName('Algoritmos e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Redes de Computadores'), required_discipline_id: getDisciplineIdByName('Programação Orientada a Objetos') },

        { discipline_id: getDisciplineIdByName('Teoria dos Grafos'), required_discipline_id: getDisciplineIdByName('Projeto e Análise de Algoritmos') },
        { discipline_id: getDisciplineIdByName('Teoria dos Números e Criptografia'), required_discipline_id: getDisciplineIdByName('Matemática Discreta') },
        { discipline_id: getDisciplineIdByName('Tópicos Interdisciplinares em Computação I'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Tópicos Interdisciplinares em Computação II'), required_discipline_id: getDisciplineIdByName('Lógica de Programação') },
        { discipline_id: getDisciplineIdByName('Tópicos Interdisciplinares em Computação III'), required_discipline_id: getDisciplineIdByName('Algoritmo e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Tópicos Interdisciplinares em Computação IV'), required_discipline_id: getDisciplineIdByName('Algoritmo e Estrutura de Dados I') },
        { discipline_id: getDisciplineIdByName('Trabalho de Graduação'), required_discipline_id: getDisciplineIdByName('Elaboração de Trabalhos Científicos e Tecnológicos em Computação') },
        { discipline_id: getDisciplineIdByName('Trabalho de Conclusão de Curso II'), required_discipline_id: getDisciplineIdByName('Trabalho de Conclusão de Curso I') },

        { discipline_id: getDisciplineIdByName('Validação e Verificação de Software'), required_discipline_id: getDisciplineIdByName('Engenharia de Software') }

    ])
}
